// Produce a classic script so the unchanged ES-module sources also run via file://.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = new URL('../src/', import.meta.url);
const modules = new Map();
const idFor = url => decodeURIComponent(url.href.slice(root.href.length));

async function collect(url) {
  const id = idFor(url);
  if (modules.has(id)) return;
  modules.set(id, '');
  const source = await readFile(url, 'utf8');
  const imports = [...source.matchAll(/^import\s+\{([^}]+)\}\s+from\s+['"]([^'"]+)['"];?\s*$/gm)];
  for (const match of imports) await collect(new URL(match[2], url));
  let transformed = source.replace(/^import\s+\{([^}]+)\}\s+from\s+['"]([^'"]+)['"];?\s*$/gm,
    (_, names, path) => `const {${names}} = load(${JSON.stringify(idFor(new URL(path, url)))});`);
  const exports = [...transformed.matchAll(/^export\s+(?:function|const|let|class)\s+(\w+)/gm)].map(match => match[1]);
  transformed = transformed.replace(/^export\s+(?=function|const|let|class)/gm, '');
  if (/^\s*(?:import|export)\s/m.test(transformed)) throw new Error(`Unsupported module syntax in ${id}`);
  modules.set(id, `${JSON.stringify(id)}: function(load) {\n${transformed}\nreturn { ${exports.join(', ')} };\n}`);
}

await collect(new URL('main.js', root));
const bundle = `// Generated by tools/build.mjs. Edit the source modules, then run node tools/build.mjs.\n(function () {\n'use strict';\nconst factories = {\n${[...modules.values()].join(',\n')}\n};\nconst cache = new Map();\nfunction load(id) {\n  if (!cache.has(id)) cache.set(id, factories[id](load));\n  return cache.get(id);\n}\nload('main.js');\n})();\n`;
await writeFile(new URL('site.js', root), bundle, 'utf8');
console.log(`Built ${modules.size} modules → ${fileURLToPath(new URL('site.js', root))}`);
