"""Build reviewed derivatives; never alter PNG masters. Requires Pillow with WebP.

The checked-in plan records each source, crop, sizes and individual quality.
Run: python tools/build-images.py [source substrings or image IDs]
"""
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
import sys
from PIL import Image, features

ROOT = Path(__file__).resolve().parents[1]
PLAN = json.loads((ROOT / 'tools/image-plan.json').read_text(encoding='utf8'))
if not features.check('webp'):
    raise RuntimeError('Pillow must support WebP')


def build(entry):
    source = ROOT / entry['source']
    if hashlib.sha256(source.read_bytes()).hexdigest() != entry['sha256']:
        raise RuntimeError(f"Master changed; review the plan: {entry['source']}")
    original = Image.open(source)
    result = {'source': entry['source'], 'sourceBytes': source.stat().st_size}
    for role, settings in entry['roles'].items():
        image = original.convert('RGBA')
        if not settings.get('lossless') and image.getchannel('A').getextrema() == (255, 255):
            image = image.convert('RGB')
        if 'crop' in settings:
            image = image.crop(tuple(settings['crop']))
        variants = []
        for width in settings['widths']:
            height = round(image.height * width / image.width)
            encoded = image if image.size == (width, height) else image.resize((width, height), Image.Resampling.LANCZOS)
            relative = f"assets/images/{role}/{entry['id']}-{width}.webp"
            target = ROOT / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            if not sys.argv[1:] or any(needle in entry['source'] or needle == entry['id'] for needle in sys.argv[1:]) or not target.exists():
                options = dict(quality=settings['quality'], method=6, lossless=settings.get('lossless', False), exact=True, alpha_quality=100)
                if original.info.get('icc_profile'):
                    options['icc_profile'] = original.info['icc_profile']
                encoded.save(target, 'WEBP', **options)
            decoded = Image.open(target).convert('RGBA')
            if decoded.size != encoded.size:
                raise RuntimeError(f'Wrong dimensions: {relative}')
            if encoded.mode == 'RGBA' and decoded.getchannel('A').tobytes() != encoded.getchannel('A').tobytes():
                raise RuntimeError(f'Alpha changed: {relative}')
            if settings.get('lossless') and decoded.tobytes() != original.convert('RGBA').tobytes():
                raise RuntimeError(f'RGBA changed: {relative}')
            variants.append({'src': './' + relative, 'width': width, 'height': height, 'bytes': target.stat().st_size})
        # Avoid a format change with negligible savings. Keep the lossless test result
        # recorded in the plan, but never use it at runtime unless it saves >= 10%.
        if role == 'mockup' and variants[0]['bytes'] > source.stat().st_size * .9:
            result[role] = {'variants': [{'src': './' + entry['source'], 'width': original.width, 'height': original.height, 'bytes': source.stat().st_size}], 'retainedPNG': True}
        else:
            result[role] = {'variants': variants, 'aspectWidth': image.width, 'aspectHeight': image.height, 'quality': settings['quality'], 'lossless': settings.get('lossless', False)}
    return entry['source'], result


with ThreadPoolExecutor(max_workers=4) as pool:
    manifest = dict(pool.map(build, PLAN))
(ROOT / 'src/shared/image-manifest.js').write_text(
    '// Generated by tools/build-images.py from the individually reviewed image plan.\n'
    + 'export const imageManifest = ' + json.dumps(manifest, ensure_ascii=False, indent=2) + ';\n', encoding='utf8')
print(f'Built and verified derivatives for {len(manifest)} masters; originals untouched.')
