// Generated by tools/build.mjs. Edit the source modules, then run node tools/build.mjs.
(function () {
'use strict';
const factories = {
"main.js": function(load) {
const { renderHero, mountHero } = load("hero/hero.js");
const { renderArk } = load("projects/ark/ark.js");
const { renderGrantmaster } = load("projects/grantmaster/grantmaster.js");
const { renderSvetlo } = load("projects/svetlo/svetlo.js");
const { renderIndustrial } = load("projects/industrial/industrial.js");
const { renderMetrika } = load("projects/metrika/metrika.js");
const { renderNewsletter } = load("projects/newsletter/newsletter.js");
const { appendProjects } = load("shared/project-separator.js");
const { mountProjectNavigation } = load("shared/project-navigation.js");
const { mountGallery } = load("shared/gallery.js");
const landing = document.querySelector('#landing');
const projects = [
  { number: 1, target: 'project-01', label: 'АРК', render: renderArk },
  { number: 2, target: 'project-02', label: 'Грантмастер', render: renderGrantmaster },
  { number: 3, target: 'project-03', label: 'SVETLO', render: renderSvetlo },
  { number: 4, target: 'project-04', label: 'Индустриальная история', render: renderIndustrial },
  { number: 5, target: 'project-05', label: 'Агент.Метрика', render: renderMetrika },
  { number: 6, target: 'project-06', label: 'Студия рассылок', render: renderNewsletter },
];
landing.append(renderHero());
appendProjects(landing, projects);
// Register only implemented projects. Future projects supply their own section IDs.
mountProjectNavigation(projects);
document.querySelectorAll('[data-gallery]').forEach(mountGallery);
mountHero(document.querySelector('.hero'));

return {  };
},
"hero/hero.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
const directory = './Вайфреймы в работу/Для горизонтального скролла в хиро блоке/';
const cards = [
  ['АРК', '1 АРК для горизонтального скролла.png'],
  ['Грантмастер', '2 Грантмастер_для горизонтального скролла.png'],
  ['SVETLO', '3 СВЕТЛО_для горизонтального скролла.png'],
  ['Индустриальная история', '4 Индустриальная история_для горизонтального скролла.png'],
  ['Агент.Метрика', '5 Агент.Метрика_для горизонтального скролла.png'],
  ['Студия рассылок', '6 Студия рассылок_для горизонтального скролла.png'],
  ['Реестр ЗАЛов', '7 Реестр залов_для горизонтального скролла.png'],
  ['8 филиалов', '8 8_филиалов_для горизонтального скролла.png'],
  ['Рабочий компас', '9 Рабочий компас_для горизонтального скролла.png'],
  ['Мобильные приложения', '10 Блок мобильных приложений_для горизонтального скролла.png'],
];
function cardImage(index) {
  const [title, file] = cards[index];
  return `<img src="${escapeHTML(directory + file)}" alt="${escapeHTML(title)}" width="1672" height="941" loading="eager" decoding="sync" draggable="false"><span class="hero-card__number" aria-hidden="true">${String(index + 1).padStart(2, '0')}</span>`;
}
function cardList(copy = false) {
  // Build every cycle before attaching the Hero. Copies retain mouse links but
  // only the original cycle participates in keyboard/screen-reader navigation.
  return `<ol class="hero-rail__cards"${copy ? ' aria-hidden="true"' : ''}>${cards.map(([title], index) => {
    const number = String(index + 1).padStart(2, '0');
    return `<li class="${copy ? 'hero-rail__copy-item' : 'hero-rail__item'}">${index < 4 ? `<a class="hero-card" href="#project-${number}"${copy ? ' tabindex="-1"' : ''} aria-label="Проект ${number}: ${escapeHTML(title)}">${cardImage(index)}</a>` : `<div class="hero-card" aria-label="Проект ${number}: ${escapeHTML(title)}">${cardImage(index)}</div>`}</li>`;
  }).join('')}</ol>`;
}
function renderHero() {
  return elementFromHTML(`
    <section class="hero" id="hero" aria-labelledby="hero-title"><div class="hero__scene">
      <header class="hero__heading"><p class="hero__name">АНДРЕЙ ПЕТРОВ</p><span class="hero__rule" aria-hidden="true"></span>
        <h1 id="hero-title"><span>Логика</span><span>и практика</span></h1>
        <ul class="hero__disciplines" aria-label="Направления работы"><li>АНАЛИЗ</li><li>КОНЦЕПЦИЯ</li><li>КУЛЬТУРА</li><li>ПРОЕКТЫ</li><li>РАЗВИТИЕ</li></ul>
      </header>
      <div class="hero-rail"><div class="hero-rail__viewport" tabindex="0" role="region" aria-label="Лента проектов: прокрутка колёсиком, перетаскиванием или стрелками">
        ${cardList(true)}${cardList()}${cardList(true)}
      </div></div>
      <footer class="hero__footer"><span class="hero__rule" aria-hidden="true"></span><p>От анализа к работающим решениям<br>в культуре, образовании и общественных проектах.</p></footer>
    </div></section>`);
}
function mountHero(hero) {
  const rail = hero.querySelector('.hero-rail__viewport');
  const first = hero.querySelector('.hero-rail__item');
  const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)');
  const behavior = () => reducedMotion.matches ? 'instant' : 'smooth';
  const list = hero.querySelector('.hero-rail__cards:not([aria-hidden])');
  const visualCards = [...rail.querySelectorAll('.hero-card')];
  visualCards.forEach((card, index) => card.dataset.heroProject = index % cards.length);
  let hoveredProject = null;
  function hoverProject(project) {
    if (project === hoveredProject) return;
    hoveredProject = project;
    visualCards.forEach(card => card.classList.toggle('is-hovered', card.dataset.heroProject === project));
  }
  rail.addEventListener('pointerover', event => hoverProject(event.target.closest('.hero-card')?.dataset.heroProject ?? null));
  rail.addEventListener('pointerleave', () => hoverProject(null));
  let frame = 0, drag = null, suppressClick = false, cycle = 0, animation = 0;
  const modulo = (value, length) => ((value % length) + length) % length;
  function setPosition(value) {
    const lower = cycle - rail.clientWidth / 2;
    const next = lower + modulo(value - lower, cycle);
    rail.scrollLeft = next;
    if (drag) drag.scroll += next - value;
  }
  function stopAnimation() { cancelAnimationFrame(animation); animation = 0; }
  function moveBy(distance) {
    stopAnimation();
    const start = rail.scrollLeft;
    if (reducedMotion.matches) { setPosition(start + distance); return; }
    const began = performance.now();
    function tick(now) {
      const progress = Math.min(1, (now - began) / 350);
      setPosition(start + distance * (1 - Math.pow(1 - progress, 3)));
      animation = progress < 1 ? requestAnimationFrame(tick) : 0;
    }
    animation = requestAnimationFrame(tick);
  }
  function update() {
    frame = 0;
    const progress = Math.max(0, Math.min(1, scrollY / hero.offsetHeight));
    hero.style.setProperty('--hero-recede', reducedMotion.matches ? 1 : 1 - progress * .08);
    hero.style.setProperty('--hero-shade', reducedMotion.matches ? 0 : progress * .18);
    hero.classList.toggle('is-covered', progress >= 1);
  }
  function schedule() { if (!frame) frame = requestAnimationFrame(update); }
  function resize() {
    stopAnimation();
    const previousCycle = cycle;
    cycle = parseFloat(getComputedStyle(list).width) + parseFloat(getComputedStyle(rail).gap);
    setPosition(previousCycle ? rail.scrollLeft * cycle / previousCycle : cycle - parseFloat(getComputedStyle(first).width) * (234 / 386));
    update();
  }
  rail.addEventListener('scroll', () => {
    const lower = cycle - rail.clientWidth / 2;
    if (cycle && (rail.scrollLeft < lower || rail.scrollLeft >= lower + cycle)) setPosition(rail.scrollLeft);
  }, { passive: true });
  rail.addEventListener('wheel', event => {
    if (event.ctrlKey) return;
    const delta = (Math.abs(event.deltaX) > Math.abs(event.deltaY) ? event.deltaX : event.deltaY) * (event.deltaMode === 1 ? 20 : event.deltaMode === 2 ? rail.clientWidth : 1);
    event.preventDefault(); stopAnimation(); setPosition(rail.scrollLeft + delta);
  }, { passive: false });
  rail.addEventListener('keydown', event => {
    if (!['ArrowLeft', 'ArrowRight'].includes(event.key)) return;
    event.preventDefault();
    moveBy((parseFloat(getComputedStyle(first).width) + parseFloat(getComputedStyle(rail).gap)) * (event.key === 'ArrowLeft' ? -1 : 1));
  });
  rail.addEventListener('pointerdown', event => {
    if (event.button !== 0 || event.pointerType !== 'mouse') return;
    stopAnimation();
    drag = { id: event.pointerId, start: event.clientX, scroll: rail.scrollLeft, moved: false }; suppressClick = false;
  });
  rail.addEventListener('dragstart', event => event.preventDefault());
  rail.addEventListener('pointermove', event => {
    const card = document.elementFromPoint(event.clientX, event.clientY)?.closest('.hero-card');
    hoverProject(card && rail.contains(card) ? card.dataset.heroProject : null);
    if (!drag || drag.id !== event.pointerId) return;
    const delta = event.clientX - drag.start;
    if (!drag.moved && Math.abs(delta) > 5) { drag.moved = true; rail.setPointerCapture(event.pointerId); rail.classList.add('is-dragging'); }
    if (drag.moved) { setPosition(drag.scroll - delta); event.preventDefault(); }
  });
  const endDrag = () => { suppressClick = !!drag?.moved; drag = null; rail.classList.remove('is-dragging'); };
  rail.addEventListener('pointerup', endDrag);
  rail.addEventListener('pointercancel', endDrag);
  rail.addEventListener('lostpointercapture', () => { if (drag) endDrag(); });
  rail.addEventListener('click', event => {
    if (suppressClick) { event.preventDefault(); suppressClick = false; return; }
    const link = event.target.closest('a[href^="#project-"]');
    if (!link || event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;
    const target = document.getElementById(link.hash.slice(1)); if (!target) return;
    event.preventDefault();
    if (location.hash !== link.hash) history.pushState(history.state, '', link.hash);
    target.scrollIntoView({ behavior: behavior() });
  });
  window.addEventListener('scroll', schedule, { passive: true });
  window.addEventListener('resize', resize);
  window.addEventListener('pageshow', update);
  reducedMotion.addEventListener('change', update);
  resize();
}

return { renderHero, mountHero };
},
"shared/dom.js": function(load) {
// Bind short Russian function words to the next word without adding line breaks.
// Unicode word boundaries avoid changing parts of words and hyphenated names.
function nonBreakingText(value) {
  return String(value).replace(
    /(?<![\p{L}\p{N}_-])(?:а|и|но|да|или|либо|как|что|чем|то|в|во|к|ко|с|со|у|о|об|обо|от|до|по|из|из-за|из-под|за|на|над|под|при|без|для|про|не|ни|же|бы|ли)[ \t]+(?=\S)/giu,
    match => match.trimEnd() + '\u00a0',
  );
}

function elementFromHTML(html) {
  const template = document.createElement('template');
  template.innerHTML = html.trim();
  // Only visible text changes: URLs, attributes, image paths and markup stay intact.
  const textNodes = document.createTreeWalker(template.content, NodeFilter.SHOW_TEXT);
  while (textNodes.nextNode()) {
    const node = textNodes.currentNode;
    if (!node.parentElement?.closest('script, style')) node.data = nonBreakingText(node.data);
  }
  return template.content.firstElementChild;
}

function escapeHTML(value) {
  return String(value).replace(/[&<>"']/g, char => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  })[char]);
}

return { nonBreakingText, elementFromHTML, escapeHTML };
},
"projects/ark/ark.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
const { ark } = load("projects/ark/data.js");
const { renderCover } = load("projects/ark/sections/cover.js");
const { renderTaskSolution } = load("projects/ark/sections/task-solution.js");
const { renderVisual } = load("projects/ark/sections/visual.js");
const { renderScreenshots } = load("projects/ark/sections/screenshots.js");
const { renderResult } = load("projects/ark/sections/result.js");
function renderArk() {
  const project = elementFromHTML('<article class="ark" id="project-01" aria-labelledby="ark-title"></article>');
  [renderCover, renderTaskSolution, renderVisual, renderScreenshots, renderResult]
    .forEach(render => project.append(render(ark)));
  return project;
}

return { renderArk };
},
"projects/ark/data.js": function(load) {
const directory = './REFERENCES/01_АРК/';
const ark = {
  url: 'https://ark-culture.ru/',
  images: {
    cover: directory + 'Атмосферный офис с сайтом «АРК».png',
    visualBackground: directory + 'Дымчатая мраморная туманность.png',
    result: directory + 'Современный дом над туманной долиной.png',
    visual: directory + '4 image 4 АРК_Приложения.png',
  },
  gallery: [
    { src: directory + '2 image 2.png', title: 'Направления работы', alt: 'АРК — раздел направлений профессиональной работы' },
    { src: directory + '3 image 3.png', title: 'Проекты', alt: 'АРК — раздел проектов и концепций' },
    { src: directory + '4 image 4 АРК_Приложения.png', title: 'Приложения', alt: 'АРК — раздел приложений: Сова и Грантмастер' },
  ],
};

return { ark };
},
"projects/ark/sections/cover.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
const { siteCTA } = load("shared/cta.js");
function renderCover(ark) {
  const section = elementFromHTML(`
    <section class="ark-cover dark-section" aria-labelledby="ark-title">
      <div class="ark-cover__content">
        <p class="project-index"><span>01</span><span class="project-index__slash">/</span>10<span class="project-index__line" aria-hidden="true"></span></p>
        <p class="eyebrow">ПРОЕКТ</p>
        <h2 id="ark-title">АРК</h2>
        <p class="ark-cover__subtitle">Анализ. Развитие. Культура.</p>
        <p class="ark-cover__description">Авторская проектная платформа, объединяющая профессиональные направления, реализованные проекты и собственные цифровые продукты.</p>
        <ul class="project-tags" aria-label="Направления проекта"><li>Веб-платформа</li><li>Проекты</li><li>Digital</li><li>Продукты</li></ul>
        ${siteCTA(ark.url)}
      </div>
    </section>`);
  section.style.setProperty('--section-image', `url("${new URL(ark.images.cover, document.baseURI).href}")`);
  return section;
}

return { renderCover };
},
"shared/cta.js": function(load) {
function siteCTA(href, label = 'Перейти на сайт') {
  return `<a class="site-cta" href="${href}" target="_blank" rel="noopener noreferrer"><span>${label}</span><span class="site-cta__arrow" aria-hidden="true">→</span></a>`;
}

return { siteCTA };
},
"projects/ark/sections/task-solution.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
function renderTaskSolution() {
  return elementFromHTML(`
    <section class="ark-task paper-section" aria-label="Задача и решение">
      <div class="ark-task__column">
        <p class="eyebrow">ЗАДАЧА</p>
        <h3>Объединить направления в единую систему</h3>
        <p>Собрать профессиональную экспертизу, проекты и собственные цифровые продукты в одной среде — с понятной структурой и возможностью развивать каждое направление независимо.</p>
      </div>
      <div class="ark-task__column ark-task__solution">
        <p class="eyebrow">РЕШЕНИЕ</p>
        <h3>Единая цифровая<br>платформа</h3>
        <p>Разработана собственная структура АРК: профессиональные направления, портфолио проектов и отдельный контур цифровых продуктов объединены общей навигацией и визуальной системой.</p>
      </div>
      <div class="ark-task__aside">
        <span class="ark-task__number" aria-hidden="true">01</span>
        <p>ОДНА СРЕДА<br>ДЛЯ ЭКСПЕРТИЗЫ,<br>ПРОЕКТОВ<br>И ПРОДУКТОВ</p>
      </div>
    </section>`);
}

return { renderTaskSolution };
},
"projects/ark/sections/visual.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
function renderVisual(ark) {
  const section = elementFromHTML(`
    <section class="ark-visual dark-section" aria-label="Ключевые разделы сайта АРК">
      <div class="ark-visual__image"><img src="${ark.images.visual}" alt="Реальный скриншот раздела приложений сайта АРК" loading="lazy" decoding="async"></div>
      <div class="ark-visual__content">
        <h3 class="eyebrow">КЛЮЧЕВЫЕ<br>РАЗДЕЛЫ САЙТА</h3>
        <ul><li>О нас</li><li>Направления</li><li>Проекты</li><li>Приложения</li><li>Подход</li><li>Контакты</li></ul>
      </div>
    </section>`);
  section.style.setProperty('--section-image', `url("${new URL(ark.images.visualBackground, document.baseURI).href}")`);
  return section;
}

return { renderVisual };
},
"projects/ark/sections/screenshots.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderScreenshots(ark) {
  return elementFromHTML(`
    <section class="ark-gallery paper-section interface-section" data-gallery aria-labelledby="ark-gallery-title">
      <div class="ark-gallery__intro">
        <p class="eyebrow interface-section__label" id="ark-gallery-title">ИНТЕРФЕЙС И РАЗДЕЛЫ</p>
        <p>Основные разделы платформы: направления работы, проекты и цифровые продукты. Каждый раздел сохраняет собственную логику внутри общей визуальной системы.</p>
      </div>
      <div class="gallery__area">
        <div class="gallery__controls" aria-label="Открыть галерею"><button type="button" data-gallery-open="2" aria-label="Открыть предыдущее изображение">←</button><button type="button" data-gallery-open="0" aria-label="Открыть первое изображение">→</button></div>
        <div class="gallery__items">
          ${ark.gallery.map((item, index) => `<figure class="gallery__item"><button class="gallery__preview" type="button" data-gallery-open="${index}" data-src="${escapeHTML(item.src)}" data-title="${escapeHTML(item.title)}" aria-label="Открыть скриншот: ${escapeHTML(item.title)}"><img src="${escapeHTML(item.src)}" alt="${escapeHTML(item.alt)}" loading="lazy" decoding="async"></button><figcaption>${escapeHTML(item.title)}</figcaption></figure>`).join('')}
        </div>
      </div>
    </section>`);
}

return { renderScreenshots };
},
"projects/ark/sections/result.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
const { siteCTA } = load("shared/cta.js");
function renderResult(ark) {
  const section = elementFromHTML(`
    <section class="ark-result dark-section" aria-labelledby="ark-result-title">
      <div><p class="eyebrow">РЕЗУЛЬТАТ</p><h3 id="ark-result-title">Единая профессиональная среда.<br>Проекты и продукты в одной системе.<br>Платформа для дальнейшего развития.</h3></div>
      <div class="ark-result__links">${siteCTA(ark.url)}</div>
    </section>`);
  section.style.setProperty('--section-image', `url("${new URL(ark.images.result, document.baseURI).href}")`);
  return section;
}

return { renderResult };
},
"projects/grantmaster/grantmaster.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
const { grantmaster } = load("projects/grantmaster/data.js");
const { renderCover } = load("projects/grantmaster/sections/cover.js");
const { renderTaskSolution } = load("projects/grantmaster/sections/task-solution.js");
const { renderLogicMap } = load("projects/grantmaster/sections/logic-map.js");
const { renderTools } = load("projects/grantmaster/sections/tools.js");
const { renderResult } = load("projects/grantmaster/sections/result.js");
function renderGrantmaster() {
  const project = elementFromHTML('<article class="grantmaster" id="project-02" aria-labelledby="grantmaster-title"></article>');
  [renderCover, renderTaskSolution, renderLogicMap, renderTools, renderResult]
    .forEach(render => project.append(render(grantmaster)));
  return project;
}

return { renderGrantmaster };
},
"projects/grantmaster/data.js": function(load) {
const directory = './REFERENCES/02_Грантмастер/';

const grantmaster = {
  url: 'https://грант-мастер.рф/',
  images: {
    cover: directory + 'Грантмастер в золотом офисе - хиро проекта.png',
    logicMap: directory + 'Тёплый офис, экран с картой проекта.png',
    result: directory + 'Золотой закат в конференц-зале.png',
  },
  tags: ['Веб-сервис', 'Продуктовый дизайн', 'UX/UI', 'Разработка'],
  logicTags: [
    ['Проблема', 'Аудитория', 'Решение', 'Цель'],
    ['Мероприятия', 'Результаты', 'Ресурсы'],
  ],
  tools: ['Конструктор проекта', 'Самопроверка', 'Итоговый паспорт'],
  gallery: [
    { src: directory + '1 Главная и диагностика.png', title: 'Главная и диагностика', alt: 'Грантмастер — главная страница и диагностика проекта' },
    { src: directory + '2 Карта логики проекта.png', title: 'Карта логики проекта', alt: 'Грантмастер — карта связей между разделами проекта' },
    { src: directory + '3 Конструктор проекта.png', title: 'Конструктор проекта', alt: 'Грантмастер — пошаговый конструктор и итоговый паспорт проекта' },
  ],
};

return { grantmaster };
},
"projects/grantmaster/sections/cover.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
const { siteCTA } = load("shared/cta.js");
function renderCover(project) {
  return elementFromHTML(`
    <section class="grantmaster-cover grantmaster__scene" aria-labelledby="grantmaster-title">
      <img class="grantmaster__scene-image" src="${escapeHTML(project.images.cover)}" alt="Грантмастер на экране ноутбука в золотом офисе" decoding="async">
      <div class="grantmaster-cover__content">
        <p class="grantmaster-cover__index"><span>02</span><span>/</span>10</p>
        <p class="eyebrow">ПРОЕКТ</p>
        <h2 id="grantmaster-title">Грантмастер</h2>
        <p class="grantmaster-cover__subtitle">Помощник в проектировании заявок и инициатив.</p>
        <p class="grantmaster__copy">Сервис, который помогает разобраться, что именно нужно проработать в проекте, последовательно выстроить его логику и подготовить основу для сильной заявки. Объединяет методику, опыт экспертов и удобные инструменты в единую систему.</p>
        <ul class="grantmaster__tags" aria-label="Направления проекта">${project.tags.map(tag => `<li>${escapeHTML(tag)}</li>`).join('')}</ul>
        ${siteCTA(project.url)}
      </div>
    </section>`);
}

return { renderCover };
},
"projects/grantmaster/sections/task-solution.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
function renderTaskSolution() {
  return elementFromHTML(`
    <section class="grantmaster-task" aria-label="Задача и решение Грантмастера">
      <div class="grantmaster-task__column">
        <p class="eyebrow">ЗАДАЧА</p>
        <h3>Упростить подготовку проектных заявок</h3>
        <p class="grantmaster__copy">Создать понятный инструмент, который помогает последовательно пройти путь от первоначальной идеи до целостного проекта — без необходимости сразу разбираться во всех требованиях конкурсов и грантовых форм.</p>
      </div>
      <div class="grantmaster-task__column grantmaster-task__solution">
        <p class="eyebrow">РЕШЕНИЕ</p>
        <h3>Единая система проектной логики</h3>
        <p class="grantmaster__copy">Цифровой помощник, который объединяет методику, образовательные материалы и пошаговый конструктор. Пользователь сначала понимает логику каждого раздела, затем заполняет его и постепенно собирает целостную модель проекта.</p>
      </div>
      <div class="grantmaster-task__marker">
        <span aria-hidden="true">02</span>
        <p>ЦИФРОВОЙ<br>ПОМОЩНИК<br>ДЛЯ ПРОЕКТНЫХ<br>ИНИЦИАТИВ</p>
      </div>
    </section>`);
}

return { renderTaskSolution };
},
"projects/grantmaster/sections/logic-map.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderLogicMap(project) {
  return elementFromHTML(`
    <section class="grantmaster-map grantmaster__scene" aria-labelledby="grantmaster-map-title">
      <img class="grantmaster__scene-image" src="${escapeHTML(project.images.logicMap)}" alt="Карта логики проекта на большом экране в тёплом офисе" loading="lazy" decoding="async">
      <div class="grantmaster-map__content">
        <p class="eyebrow">КАРТА ЛОГИКИ ПРОЕКТА</p>
        <h3 id="grantmaster-map-title">Проект сильнее,<br>когда его части<br>связаны между собой.</h3>
        <p class="grantmaster__copy">Карта показывает проект не как набор отдельных полей, а как единую систему: от проблемы и аудитории до реализации, результатов и ресурсов.</p>
        <div class="grantmaster-map__tags">${project.logicTags.map(row => `<ul class="grantmaster__tags">${row.map(tag => `<li>${escapeHTML(tag)}</li>`).join('')}</ul>`).join('')}</div>
      </div>
    </section>`);
}

return { renderLogicMap };
},
"projects/grantmaster/sections/tools.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderTools(project) {
  return elementFromHTML(`
    <section class="grantmaster-tools interface-section" data-gallery aria-labelledby="grantmaster-tools-title">
      <div class="grantmaster-tools__intro">
        <p class="eyebrow interface-section__label" id="grantmaster-tools-title">ИНТЕРФЕЙС И РАЗДЕЛЫ</p>
        <p class="grantmaster__copy">«Грантмастер» сочетает обучение и практическую работу: объясняет логику каждого раздела, показывает сильные и слабые примеры и помогает последовательно собрать проект в единую систему.</p>
      </div>
      <div class="grantmaster-tools__screenshots">
        <div class="grantmaster-tools__previews">${project.gallery.map((item, index) => `<figure class="grantmaster-tools__item"><button class="grantmaster-tools__preview" type="button" data-gallery-open="${index}" data-src="${escapeHTML(item.src)}" data-title="${escapeHTML(item.title)}" aria-label="Открыть скриншот: ${escapeHTML(item.title)}"><img src="${escapeHTML(item.src)}" alt="${escapeHTML(item.alt)}" loading="lazy" decoding="async"></button><figcaption>${escapeHTML(item.title)}</figcaption></figure>`).join('')}</div>
      </div>
    </section>`);
}

return { renderTools };
},
"projects/grantmaster/sections/result.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
const { siteCTA } = load("shared/cta.js");
function renderResult(project) {
  return elementFromHTML(`
    <section class="grantmaster-result grantmaster__scene" aria-labelledby="grantmaster-result-title">
      <img class="grantmaster__scene-image" src="${escapeHTML(project.images.result)}" alt="Золотой закат за окнами конференц-зала" loading="lazy" decoding="async">
      <div class="grantmaster-result__content">
        <p class="eyebrow">РЕЗУЛЬТАТ</p>
        <h3 id="grantmaster-result-title">Больше сильных<br>проектов и инициатив</h3>
        <p class="grantmaster__copy">«Грантмастер» помогает превратить первоначальную идею в понятный, логически связанный и аргументированный проект, который можно использовать как основу для подготовки заявки.</p>
      </div>
      <div class="grantmaster-result__action">${siteCTA(project.url)}</div>
    </section>`);
}

return { renderResult };
},
"projects/svetlo/svetlo.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
const { svetlo } = load("projects/svetlo/data.js");
const { renderCover } = load("projects/svetlo/sections/cover.js");
const { renderTaskSolution } = load("projects/svetlo/sections/task-solution.js");
const { renderCollection } = load("projects/svetlo/sections/collection.js");
const { renderScreenshots } = load("projects/svetlo/sections/screenshots.js");
const { renderResult } = load("projects/svetlo/sections/result.js");
function renderSvetlo() {
  const project = elementFromHTML('<article class="svetlo" id="project-03" aria-labelledby="svetlo-title"></article>');
  [renderCover, renderTaskSolution, renderCollection, renderScreenshots, renderResult]
    .forEach(render => project.append(render(svetlo)));
  return project;
}

return { renderSvetlo };
},
"projects/svetlo/data.js": function(load) {
const directory = './REFERENCES/03_Светло/';

const svetlo = {
  images: {
    cover: directory + '1 Хиро.png',
    collection: directory + '2 блок.png',
    result: directory + '3 подвал.png',
  },
  tags: ['Яндекс КИТ', 'Дизайн', 'Интерьеры', 'Витрина'],
  categories: ['Скандинавская коллекция', 'Потолочный', 'Настенный', 'Настольный', 'Напольный', 'Ванная / санузел', 'Блог'],
  gallery: [
    { src: directory + '2.png', title: 'Скандинавская коллекция', alt: 'SVETLO — скандинавская коллекция интерьерного освещения' },
    { src: directory + '3.png', title: 'Настенный свет', alt: 'SVETLO — каталог настенного освещения' },
    { src: directory + '4.png', title: 'Подход и журнал', alt: 'SVETLO — философия света, подписка и журнал о свете и пространстве' },
    { src: directory + '5.png', title: 'Полная страница', alt: 'SVETLO — полная страница интернет-магазина с коллекциями и категориями' },
  ],
};

return { svetlo };
},
"projects/svetlo/sections/cover.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderCover(project) {
  return elementFromHTML(`
    <section class="svetlo-cover" aria-labelledby="svetlo-title">
      <img class="svetlo-cover__image" src="${escapeHTML(project.images.cover)}" alt="SVETLO на планшете в тёплом светлом интерьере" decoding="async">
      <div class="svetlo-cover__content">
        <p class="svetlo__number"><span>03</span> / 10 <i aria-hidden="true"></i></p>
        <p class="eyebrow">ПРОЕКТ</p>
        <h2 id="svetlo-title">SVETLO</h2>
        <p class="svetlo-cover__subtitle">Интернет-магазин премиального интерьерного освещения, созданный на Яндекс КИТ.</p>
        <p class="svetlo__copy">Проект показывает, как можно соединить полноценную структуру интернет-магазина с визуальной подачей, в которой свет рассматривается не только как товар, но и как часть пространства.</p>
        <ul class="svetlo__tags">${project.tags.map(tag => `<li>${escapeHTML(tag)}</li>`).join('')}</ul>
      </div>
    </section>`);
}

return { renderCover };
},
"projects/svetlo/sections/task-solution.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
function renderTaskSolution() {
  return elementFromHTML(`
    <section class="svetlo-task" aria-label="Задача и решение проекта SVETLO">
      <div class="svetlo-task__column">
        <p class="eyebrow">ЗАДАЧА</p>
        <h3>Показать коллекцию<br>в современном формате</h3>
        <p class="svetlo__copy">Соединить выбор освещения с пониманием его роли в интерьере: показать коллекции, категории и товары в контексте пространства и сделать переход к конкретному решению понятным.</p>
      </div>
      <div class="svetlo-task__column svetlo-task__solution">
        <p class="eyebrow">РЕШЕНИЕ</p>
        <h3>Готовый магазин<br>на Яндекс КИТ</h3>
        <p class="svetlo__copy">Полноценная структура интернет-магазина на Яндекс КИТ: категории, коллекции и карточки товаров дополнены крупными интерьерными сценами. Визуальная подача связывает образ пространства с выбором освещения.</p>
      </div>
      <div class="svetlo-task__marker" aria-hidden="true">
        <span>03</span><i></i><p>ИНТЕРНЕТ-МАГАЗИН<br>ОСВЕЩЕНИЯ<br>НА БАЗЕ<br>ЯНДЕКС КИТ</p>
      </div>
    </section>`);
}

return { renderTaskSolution };
},
"projects/svetlo/sections/collection.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderCollection(project) {
  return elementFromHTML(`
    <section class="svetlo-collection" aria-labelledby="svetlo-collection-title">
      <div class="svetlo-collection__intro">
        <div><p class="eyebrow">КОЛЛЕКЦИИ И КАТЕГОРИИ</p><h3 id="svetlo-collection-title">Свет, который<br>создаёт пространство.</h3></div>
        <div class="svetlo-collection__description">
          <p class="svetlo__copy">Категории, коллекции и карточки товаров дополняются крупными интерьерными сценами: покупатель видит светильник в контексте и может перейти от образа интерьера к выбору конкретного решения.</p>
          <ul class="svetlo__tags">${project.categories.map(category => `<li>${escapeHTML(category)}</li>`).join('')}</ul>
        </div>
      </div>
      <img class="svetlo-collection__image" src="${escapeHTML(project.images.collection)}" width="2232" height="705" alt="Тёплый интерьер спальни с настенными светильниками — сцена проекта SVETLO" loading="lazy" decoding="async">
    </section>`);
}

return { renderCollection };
},
"projects/svetlo/sections/screenshots.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderScreenshots(project) {
  return elementFromHTML(`
    <section class="svetlo-gallery interface-section" data-gallery aria-labelledby="svetlo-gallery-title">
      <div class="svetlo-gallery__intro"><p class="eyebrow interface-section__label" id="svetlo-gallery-title">ИНТЕРФЕЙС И РАЗДЕЛЫ</p><p class="svetlo__copy">Коллекция, каталог, журнал и полная страница магазина. Скриншоты открываются в полном размере, их можно листать и увеличивать.</p></div>
      <div class="svetlo-gallery__previews">${project.gallery.map((item, index) => `
        <figure class="svetlo-gallery__item"><button type="button" class="svetlo-gallery__preview" data-gallery-open="${index}" data-src="${escapeHTML(item.src)}" data-title="${escapeHTML(item.title)}" aria-label="Открыть скриншот: ${escapeHTML(item.title)}"><img src="${escapeHTML(item.src)}" alt="${escapeHTML(item.alt)}" loading="lazy" decoding="async"></button><figcaption>${escapeHTML(item.title)}</figcaption></figure>`).join('')}
      </div>
    </section>`);
}

return { renderScreenshots };
},
"projects/svetlo/sections/result.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderResult(project) {
  return elementFromHTML(`
    <section class="svetlo-result" aria-labelledby="svetlo-result-title">
      <img class="svetlo-result__image" src="${escapeHTML(project.images.result)}" alt="Интерьер SVETLO с креслом и скульптурным напольным светильником" loading="lazy" decoding="async">
      <div class="svetlo-result__content"><p class="eyebrow">РЕЗУЛЬТАТ</p><h3 id="svetlo-result-title">Стильный магазин<br>для вдохновения<br>и продаж</h3><p class="svetlo__copy">Готовый пример современного интернет-магазина освещения, который демонстрирует возможности Яндекс КИТ и может использоваться как портфолио для витрин платформы.</p></div>
    </section>`);
}

return { renderResult };
},
"projects/industrial/industrial.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
const { industrial } = load("projects/industrial/data.js");
const { renderCover } = load("projects/industrial/sections/cover.js");
const { renderTaskSolution } = load("projects/industrial/sections/task-solution.js");
const { renderHistory } = load("projects/industrial/sections/history.js");
const { renderScreenshots } = load("projects/industrial/sections/screenshots.js");
const { renderResult } = load("projects/industrial/sections/result.js");
function renderIndustrial() {
  const project = elementFromHTML('<article class="industrial" id="project-04" aria-labelledby="industrial-title"></article>');
  [renderCover, renderTaskSolution, renderHistory, renderScreenshots, renderResult]
    .forEach(render => project.append(render(industrial)));
  return project;
}

return { renderIndustrial };
},
"projects/industrial/data.js": function(load) {
const directory = './REFERENCES/04_Индустриальная история/';

const industrial = {
  images: {
    cover: directory + '1 Хиро Индустриальный архив на закате.png',
    history: directory + '2 Индустриальный город над рекой.png',
    result: directory + '3 Стальной мост на закате над рекой_подвал.png',
  },
  gallery: [
    { src: directory + '3.png', title: 'История района', alt: 'История индустриального района — исторический таймлайн цифрового музея' },
    { src: directory + '4.png', title: 'Каталог объектов', alt: 'Каталог объектов промышленного наследия Красногвардейского района' },
    { src: directory + '5.png', title: 'Тематические исследования', alt: 'Тематические исследования индустриальной истории района' },
    { src: directory + '6.png', title: 'Полная страница', alt: 'Полная страница концепции цифрового музея индустриальной истории' },
  ],
  copy: {
    cover: 'Концепция цифрового музея индустриальной истории Красногвардейского района Санкт-Петербурга: история района, промышленное наследие, архивные материалы и тематические исследования.',
    task: 'Создать современную концепцию цифрового музея, объединяющего историю промышленного развития Красногвардейского района, предприятия, инфраструктуру, архивные материалы и визуальные свидетельства разных эпох. Сделать исторический материал понятным, наглядным и доступным для широкой аудитории.',
    solution: 'Разработана структура и интерактивный прототип цифрового музея: исторический таймлайн, каталог объектов промышленного наследия, визуальный архив и тематические исследования. Для проекта создана единая визуальная система, объединяющая архивную эстетику и современный цифровой интерфейс.',
    marker: 'КОНЦЕПЦИЯ ЦИФРОВОГО МУЗЕЯ ИНДУСТРИАЛЬНОЙ ИСТОРИИ КРАСНОГВАРДЕЙСКОГО РАЙОНА САНКТ-ПЕТЕРБУРГА',
    history: 'История района раскрывается через предприятия, инфраструктуру, городскую среду и архивные свидетельства — от первых промышленных производств на Охте до индустриального наследия XX века и современных объектов.',
    gallery: 'Концепция построена вокруг четырёх взаимосвязанных направлений: истории индустриального развития района, каталога объектов промышленного наследия, визуального архива и тематических исследований. Каждый раздел формирует собственный маршрут знакомства с материалами цифрового музея.',
    result: 'Разработанная концепция показывает, как разрозненные исторические материалы, архивные фотографии, документы и сведения об объектах промышленного наследия можно объединить в единую цифровую среду — современную, визуально выразительную и удобную для исследования истории района.',
  },
};

return { industrial };
},
"projects/industrial/sections/cover.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderCover(project) {
  return elementFromHTML(`
    <section class="industrial-cover" aria-labelledby="industrial-title">
      <img class="industrial-cover__image" src="${escapeHTML(project.images.cover)}" alt="Индустриальный архив на закате с прототипом цифрового музея на мониторе" decoding="async">
      <div class="industrial-cover__content">
        <p class="industrial__number"><span>04</span> / 10 <i aria-hidden="true"></i></p>
        <p class="eyebrow">ПРОЕКТ</p>
        <h2 id="industrial-title">Индустриальный музей<br><span>Красногвардейского<br>района</span></h2>
        <p class="industrial__copy">${escapeHTML(project.copy.cover)}</p>
      </div>
    </section>`);
}

return { renderCover };
},
"projects/industrial/sections/task-solution.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderTaskSolution(project) {
  return elementFromHTML(`
    <section class="industrial-task" aria-label="Задача и решение проекта индустриального музея">
      <div class="industrial-task__column"><p class="eyebrow">ЗАДАЧА</p><h3>Представить промышленное наследие района в цифровом формате</h3><p class="industrial__copy">${escapeHTML(project.copy.task)}</p></div>
      <div class="industrial-task__column industrial-task__solution"><p class="eyebrow">РЕШЕНИЕ</p><h3>Концепция<br>цифрового музея</h3><p class="industrial__copy">${escapeHTML(project.copy.solution)}</p></div>
      <div class="industrial-task__marker"><span aria-hidden="true">04</span><i aria-hidden="true"></i><p>${escapeHTML(project.copy.marker)}</p></div>
    </section>`);
}

return { renderTaskSolution };
},
"projects/industrial/sections/history.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderHistory(project) {
  return elementFromHTML(`
    <section class="industrial-history" aria-labelledby="industrial-history-title">
      <img class="industrial-history__image" src="${escapeHTML(project.images.history)}" alt="Архивная панорама индустриального города над рекой" loading="lazy" decoding="async">
      <div class="industrial-history__content"><p class="eyebrow">ИСТОРИЯ РАЙОНА</p><h3 id="industrial-history-title">Заводы. Люди.<br>Город.</h3><p class="industrial__copy">${escapeHTML(project.copy.history)}</p></div>
    </section>`);
}

return { renderHistory };
},
"projects/industrial/sections/screenshots.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderScreenshots(project) {
  return elementFromHTML(`
    <section class="industrial-gallery interface-section" data-gallery aria-labelledby="industrial-gallery-title">
      <div class="industrial-gallery__intro"><p class="eyebrow interface-section__label" id="industrial-gallery-title">ИНТЕРФЕЙС И РАЗДЕЛЫ</p><p class="industrial__copy">${escapeHTML(project.copy.gallery)}</p></div>
      <div class="industrial-gallery__previews">${project.gallery.map((item, index) => `<figure class="industrial-gallery__item"><button type="button" class="industrial-gallery__preview" data-gallery-open="${index}" data-src="${escapeHTML(item.src)}" data-title="${escapeHTML(item.title)}" aria-label="Открыть изображение: ${escapeHTML(item.title)}"><img src="${escapeHTML(item.src)}" alt="${escapeHTML(item.alt)}" loading="lazy" decoding="async"></button><figcaption>${escapeHTML(item.title)}</figcaption></figure>`).join('')}</div>
    </section>`);
}

return { renderScreenshots };
},
"projects/industrial/sections/result.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderResult(project) {
  return elementFromHTML(`
    <section class="industrial-result" aria-labelledby="industrial-result-title">
      <img class="industrial-result__image" src="${escapeHTML(project.images.result)}" alt="Стальной мост на закате над рекой" loading="lazy" decoding="async">
      <div class="industrial-result__content"><p class="eyebrow">РЕЗУЛЬТАТ</p><h3 id="industrial-result-title">Цифровая среда<br>для истории района</h3><p class="industrial__copy">${escapeHTML(project.copy.result)}</p></div>
    </section>`);
}

return { renderResult };
},
"projects/metrika/metrika.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
const { metrika } = load("projects/metrika/data.js");
const { renderCover } = load("projects/metrika/sections/cover.js");
const { renderInformation } = load("projects/metrika/sections/information.js");
const { renderScreenshots } = load("projects/metrika/sections/screenshots.js");
function renderMetrika() {
  const project = elementFromHTML('<article class="metrika" id="project-05" aria-labelledby="metrika-title"></article>');
  [renderCover, renderInformation, renderScreenshots].forEach(render => project.append(render(metrika)));
  return project;
}

return { renderMetrika };
},
"projects/metrika/data.js": function(load) {
const directory = './REFERENCES/05_Агент.Метрика/';

const metrika = {
  tags: ['Аналитика', 'Яндекс.Метрика', 'Цифровые фонды', 'Исследования'],
  copy: {
    cover: 'Веб-сервис для анализа посещаемости, контента и поведения аудитории сайтов культурных учреждений. Помогает увидеть ключевые показатели, сравнить периоды, понять интерес пользователей к материалам и получить готовые аналитические выводы.',
    taskTitle: 'Превратить данные посещаемости в понятную аналитику',
    task: 'Создать инструмент для сотрудников библиотек, музеев и других учреждений культуры, который помогает работать с данными веб-аналитики без необходимости самостоятельно разбираться в большом количестве показателей и отчётов.',
    solution: 'Сервис структурирует данные веб-аналитики и показывает их в понятной форме: ключевые показатели, динамику посещаемости, источники трафика, географию аудитории и интерес к контенту. Периоды можно сравнивать между собой, а результаты — использовать для анализа и подготовки отчётов.',
    gallery: 'Все ключевые сценарии — от общей сводки до сравнения периодов, анализа динамики и подробного отчёта. Нажмите на миниатюру, чтобы открыть экран в полном размере.',
  },
  features: [
    { icon: 'indicators', title: 'Ключевые показатели', text: 'Посещаемость, глубина просмотра, время на сайте и возвращаемость аудитории — основные показатели собраны в одной сводке.' },
    { icon: 'calendar', title: 'Сравнение периодов', text: 'Сопоставление выбранных периодов помогает быстро увидеть рост, снижение и изменение ключевых показателей.' },
    { icon: 'content', title: 'Контент и интерес', text: 'Популярные материалы и страницы показывают, какие темы и цифровые коллекции привлекают наибольшее внимание аудитории.' },
    { icon: 'report', title: 'Отчёты и выводы', text: 'Структурированный отчёт объединяет показатели, динамику и основные наблюдения за выбранный период.' },
  ],
  gallery: [
    { src: directory + '1_Агент.Метрика_ Главная.png', width: 1920, height: 1599, title: 'Главный экран', alt: 'Главный экран Агент.Метрики: показатели, материалы, география и аналитический вывод' },
    { src: directory + '2_Агент.Метрика_ Сравнение периодов.png', width: 1920, height: 578, title: 'Сравнение периодов', alt: 'Сравнение показателей двух выбранных периодов' },
    { src: directory + '3_Агент.Метрика_ Сравнение периодов.png', width: 1577, height: 559, title: 'Динамика посещаемости', alt: 'График динамики посещаемости для двух периодов' },
    { src: directory + '4_Агент.Метрика_ Отчеты.png', width: 1908, height: 1061, title: 'Отчёты', alt: 'Отчёт с резюме периода, показателями и динамикой посещаемости' },
  ],
};

return { metrika };
},
"projects/metrika/sections/cover.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderCover(project) {
  const screen = project.gallery[0];
  return elementFromHTML(`
    <section class="metrika-cover dark-section" aria-labelledby="metrika-title">
      <div class="metrika-cover__content">
        <p class="metrika__number"><span>05</span> / 10 <i aria-hidden="true"></i></p>
        <p class="eyebrow">ПРОЕКТ</p>
        <h2 id="metrika-title">Агент.Метрика</h2>
        <p class="metrika-cover__subtitle">Помощник исследователя<br>цифровых фондов</p>
        <p class="metrika__copy">${escapeHTML(project.copy.cover)}</p>
        <ul class="metrika-cover__tags" aria-label="Направления проекта">${project.tags.map(tag => `<li>${escapeHTML(tag)}</li>`).join('')}</ul>
      </div>
      <div class="metrika-cover__visual"><img class="metrika-cover__divider" src="./Вайфреймы в работу/Line.svg" width="29" height="1104" alt="" aria-hidden="true"><img class="metrika-cover__screen" src="${escapeHTML(screen.src)}" width="${screen.width}" height="${screen.height}" alt="${escapeHTML(screen.alt)}" decoding="sync"></div>
    </section>`);
}

return { renderCover };
},
"projects/metrika/sections/information.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
const icons = {
  indicators: '<path d="M5 21v-5m7 5V9m7 12V3" stroke-width="5"/>',
  calendar: '<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2v6m10-6v6M3 11h18M7 15h2m6 0h2m-10 3h2m6 0h2"/>',
  content: '<path d="M14 2H5v20h14V7zM14 2v6h5M8 12h8m-8 4h8"/>',
  report: '<path d="M4 3h16v18H4zM8 8h8m-8 4h8m-8 4h5"/>',
};

function renderInformation(project) {
  return elementFromHTML(`
    <section class="metrika-information paper-section" aria-label="Задача, решение и возможности сервиса">
      <div class="metrika-information__task"><p class="eyebrow">ЗАДАЧА</p><h3>${escapeHTML(project.copy.taskTitle)}</h3><p class="metrika__copy">${escapeHTML(project.copy.task)}</p></div>
      <div class="metrika-information__solution"><p class="eyebrow">РЕШЕНИЕ</p><h3>Агент.Метрика</h3><p class="metrika__copy">${escapeHTML(project.copy.solution)}</p></div>
      <ul class="metrika-information__features" aria-label="Возможности сервиса">${project.features.map(feature => `<li><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[feature.icon]}</svg><div><h4>${escapeHTML(feature.title)}</h4><p>${escapeHTML(feature.text)}</p></div></li>`).join('')}</ul>
    </section>`);
}

return { renderInformation };
},
"projects/metrika/sections/screenshots.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderScreenshots(project) {
  return elementFromHTML(`
    <section class="metrika-gallery dark-section interface-section" data-gallery aria-labelledby="metrika-gallery-title">
      <div class="metrika-gallery__intro"><p class="eyebrow interface-section__label" id="metrika-gallery-title">ИНТЕРФЕЙС И РАЗДЕЛЫ</p><p class="metrika__copy">${escapeHTML(project.copy.gallery)}</p></div>
      <div class="metrika-gallery__previews">${project.gallery.map((screen, index) => `<figure class="metrika-gallery__item"><button type="button" class="metrika-gallery__preview" data-gallery-open="${index}" data-src="${escapeHTML(screen.src)}" data-title="${escapeHTML(screen.title)}" aria-label="Открыть скриншот: ${escapeHTML(screen.title)}"><img src="${escapeHTML(screen.src)}" width="${screen.width}" height="${screen.height}" alt="${escapeHTML(screen.alt)}" loading="lazy" decoding="async"></button><figcaption>${escapeHTML(screen.title)}</figcaption></figure>`).join('')}</div>
    </section>`);
}

return { renderScreenshots };
},
"projects/newsletter/newsletter.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
const { newsletter } = load("projects/newsletter/data.js");
const { renderSidebar } = load("projects/newsletter/sections/sidebar.js");
const { renderCover } = load("projects/newsletter/sections/cover.js");
const { renderInformation } = load("projects/newsletter/sections/information.js");
const { renderScreenshots } = load("projects/newsletter/sections/screenshots.js");
function renderNewsletter() {
  const project = elementFromHTML('<article class="newsletter" id="project-06" aria-labelledby="newsletter-title"></article>');
  const sections = elementFromHTML('<div class="newsletter__sections"></div>');
  [renderCover, renderInformation, renderScreenshots].forEach(render => sections.append(render(newsletter)));
  project.append(renderSidebar(newsletter), sections);
  return project;
}

return { renderNewsletter };
},
"projects/newsletter/data.js": function(load) {
const directory = './REFERENCES/06_Студия рассылок/';

const newsletter = {
  background: directory + 'Фон.png',
  tags: ['Новости', 'Фонды', 'События', 'Публикации'],
  copy: {
    subtitle: 'Дайджесты и посты для культурных организаций',
    cover: 'Локальный сервис, который собирает материалы с сайта организации, отбирает и структурирует их и помогает создавать готовые выпуски рассылок и публикации для социальных сетей.',
    taskTitle: 'Сократить путь от материалов сайта до готовой рассылки',
    task: [
      'Сотрудникам культурных организаций приходится вручную искать публикации на сайте, отбирать материалы, сокращать тексты, подбирать изображения и заново собирать их в формат рассылки или поста.',
      'Задача проекта — объединить этот процесс в одном инструменте и сократить объём повторяющейся редакторской работы.',
    ],
    solution: [
      'Сервис собирает материалы из выбранных разделов сайта, позволяет задать тематику и параметры выпуска, а затем формирует несколько вариантов готового материала.',
      'Результат можно просмотреть в десктопном и мобильном формате, отредактировать, скопировать или экспортировать для дальнейшего использования.',
    ],
    gallery: [
      'Пользователь указывает сайт, выбирает разделы и тематику, задаёт объём и дополнительные параметры. Студия собирает подходящие материалы и формирует несколько вариантов выпуска.',
      'Готовый результат можно проверить в разных форматах, отредактировать и экспортировать — весь рабочий цикл остаётся внутри одного интерфейса.',
    ],
  },
  features: [
    { title: 'АВТОМАТИЧЕСКИЙ СБОР', text: 'Материалы собираются непосредственно с сайта организации из выбранных пользователем разделов.' },
    { title: 'РАССЫЛКИ И СОЦСЕТИ', text: 'Один интерфейс позволяет создавать как полноценные email-дайджесты, так и отдельные публикации для социальных сетей.' },
    { title: 'КОНТРОЛЬ РЕЗУЛЬТАТА', text: 'Несколько вариантов генерации, предпросмотр для компьютера и телефона, редактирование, копирование и экспорт готового материала.' },
  ],
  images: [
    { src: directory + '1.png', width: 622, height: 1620, title: 'Настройка выпуска', alt: 'Студия рассылок: настройка источника, тематики и параметров выпуска' },
    { src: directory + '2.png', width: 598, height: 951, title: 'Настройка соцсетей', alt: 'Студия рассылок: настройка публикации для социальных сетей' },
    { src: directory + '3.png', width: 1299, height: 1520, title: 'Публикация для соцсетей', alt: 'Студия рассылок: готовая публикация с вариантами и инструментами редактирования' },
    { src: directory + '4.png', width: 1921, height: 2938, title: 'Готовая рассылка', alt: 'Студия рассылок: сформированный дайджест и панель настройки выпуска' },
  ],
};

return { newsletter };
},
"projects/newsletter/sections/sidebar.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderSidebar(project) {
  const screen = project.images[0];
  return elementFromHTML(`
    <aside class="newsletter-sidebar" aria-label="Экран настройки выпуска Студии рассылок">
      <img class="newsletter-sidebar__screen" src="${escapeHTML(screen.src)}" width="${screen.width}" height="${screen.height}" alt="${escapeHTML(screen.alt)}" decoding="sync">
      <img class="newsletter-sidebar__line" src="./Вайфреймы в работу/Line.svg" width="29" height="1104" alt="" aria-hidden="true">
    </aside>`);
}

return { renderSidebar };
},
"projects/newsletter/sections/cover.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderCover(project) {
  return elementFromHTML(`
    <section class="newsletter-cover dark-section" aria-labelledby="newsletter-title">
      <img class="newsletter-cover__background" src="${escapeHTML(project.background)}" width="1672" height="940" alt="" aria-hidden="true" decoding="async">
      <div class="newsletter-cover__content">
        <p class="newsletter__number"><span>06</span> / 10 <i aria-hidden="true"></i></p>
        <p class="eyebrow">ПРОЕКТ</p>
        <h2 id="newsletter-title">Студия рассылок</h2>
        <p class="newsletter-cover__subtitle">${escapeHTML(project.copy.subtitle)}</p>
        <p class="newsletter__copy">${escapeHTML(project.copy.cover)}</p>
        <ul class="newsletter-cover__tags" aria-label="Направления проекта">${project.tags.map(tag => `<li>${escapeHTML(tag)}</li>`).join('')}</ul>
      </div>
    </section>`);
}

return { renderCover };
},
"projects/newsletter/sections/information.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderInformation(project) {
  return elementFromHTML(`
    <section class="newsletter-information paper-section" aria-label="Задача, решение и преимущества Студии рассылок">
      <div class="newsletter-information__task"><p class="eyebrow">ЗАДАЧА</p><h3>${escapeHTML(project.copy.taskTitle)}</h3>${project.copy.task.map(text => `<p class="newsletter__copy">${escapeHTML(text)}</p>`).join('')}</div>
      <div class="newsletter-information__solution"><p class="eyebrow">РЕШЕНИЕ</p><h3>Студия рассылок</h3>${project.copy.solution.map(text => `<p class="newsletter__copy">${escapeHTML(text)}</p>`).join('')}</div>
      <ul class="newsletter-information__features" aria-label="Преимущества сервиса">${project.features.map(feature => `<li><span class="newsletter-information__accent" aria-hidden="true"></span><div><h4>${escapeHTML(feature.title)}</h4><p>${escapeHTML(feature.text)}</p></div></li>`).join('')}</ul>
    </section>`);
}

return { renderInformation };
},
"projects/newsletter/sections/screenshots.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function renderScreenshots(project) {
  return elementFromHTML(`
    <section class="newsletter-gallery dark-section interface-section" data-gallery aria-labelledby="newsletter-gallery-title">
      <div class="newsletter-gallery__intro"><p class="eyebrow interface-section__label" id="newsletter-gallery-title">ИНТЕРФЕЙС И РАЗДЕЛЫ</p>${project.copy.gallery.map(text => `<p class="newsletter__copy">${escapeHTML(text)}</p>`).join('')}<p class="newsletter-gallery__count">4 экрана</p></div>
      <div class="newsletter-gallery__previews">${project.images.map((screen, index) => `<figure class="newsletter-gallery__item"><button type="button" class="newsletter-gallery__preview" data-gallery-open="${index}" data-src="${escapeHTML(screen.src)}" data-title="${escapeHTML(screen.title)}" aria-label="Открыть скриншот: ${escapeHTML(screen.title)}"><img src="${escapeHTML(screen.src)}" width="${screen.width}" height="${screen.height}" alt="${escapeHTML(screen.alt)}" loading="lazy" decoding="async"></button><figcaption>${escapeHTML(screen.title)}</figcaption></figure>`).join('')}</div>
    </section>`);
}

return { renderScreenshots };
},
"shared/project-separator.js": function(load) {
const { elementFromHTML } = load("shared/dom.js");
function renderProjectSeparator() {
  return elementFromHTML('<div class="project-separator" aria-hidden="true"><img src="./Вайфреймы в работу/Разделитель.svg" width="5506" height="70" alt="" decoding="async"></div>');
}

// Keep the separator outside project modules and insert it at every project boundary.
function appendProjects(container, projects) {
  projects.forEach((project, index) => {
    if (index > 0) container.append(renderProjectSeparator());
    container.append(project.render());
  });
}

return { renderProjectSeparator, appendProjects };
},
"shared/project-navigation.js": function(load) {
const { elementFromHTML, escapeHTML } = load("shared/dom.js");
function mountProjectNavigation(projects, total = 10) {
  const available = new Map(projects.map(project => [project.number, project]));
  const titles = ['АРК', 'Грантмастер', 'SVETLO', 'Индустриальная история', 'Агент.Метрика', 'Студия рассылок', 'Реестр ЗАЛов', '8 филиалов', 'Рабочий компас', 'Мобильные приложения'];
  const navigation = elementFromHTML(`<nav class="project-navigation" tabindex="0" aria-label="Навигация по проектам"><ol>${Array.from({ length: total }, (_, index) => {
    const number = index + 1;
    const label = String(number).padStart(2, '0');
    const project = available.get(number);
    const title = escapeHTML(project?.label || titles[index] || `Проект ${label}`);
    const content = `<span class="project-navigation__number">${label}</span><span class="project-navigation__name">${title}</span>`;
    return `<li>${project ? `<a href="#${escapeHTML(project.target)}" aria-label="Проект ${label}: ${title}" ${number === 1 ? 'aria-current="location"' : ''}>${content}</a>` : `<span class="project-navigation__unavailable" aria-disabled="true" aria-label="Проект ${label}: ${title}, пока недоступен">${content}</span>`}</li>`;
  }).join('')}</ol></nav>`);
  document.body.append(navigation);
  const onNavigate = event => {
    const link = event.target.closest('a[href^="#"]');
    if (!link || event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;
    const target = document.getElementById(link.hash.slice(1));
    if (!target) return;
    event.preventDefault();
    if (location.hash !== link.hash) history.pushState(history.state, '', link.hash);
    target.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' });
  };
  navigation.addEventListener('click', onNavigate);
  let pointerFocus = false;
  const onPointerDown = event => {
    pointerFocus = navigation.contains(event.target);
    if (pointerFocus) navigation.focus({ preventScroll: true });
    else if (navigation.contains(document.activeElement)) document.activeElement.blur();
  };
  const onPointerLeave = () => {
    if (pointerFocus && navigation.contains(document.activeElement)) document.activeElement.blur();
    pointerFocus = false;
  };
  document.addEventListener('pointerdown', onPointerDown);
  navigation.addEventListener('pointerleave', onPointerLeave);
  navigation.addEventListener('keydown', event => {
    pointerFocus = false;
    if (event.key === 'Escape') document.activeElement.blur();
  });
  const sections = projects.map(project => document.getElementById(project.target)).filter(Boolean);
  let frame = 0;
  function updateActiveProject() {
    frame = 0;
    // Recompute actual boundaries even when scrolling jumps across large articles.
    let active = sections[0];
    const readingLine = Math.min(160, window.innerHeight * .15);
    for (const section of sections) {
      if (section.getBoundingClientRect().top <= readingLine) active = section;
    }
    navigation.querySelectorAll('a').forEach(link => {
      if (active && link.hash === `#${active.id}`) link.setAttribute('aria-current', 'location');
      else link.removeAttribute('aria-current');
    });
  }
  const scheduleUpdate = () => {
    if (!frame) frame = requestAnimationFrame(updateActiveProject);
  };
  window.addEventListener('scroll', scheduleUpdate, { passive: true });
  window.addEventListener('resize', scheduleUpdate);
  const observer = new ResizeObserver(scheduleUpdate);
  sections.forEach(section => observer.observe(section));
  updateActiveProject();
  return () => {
    observer.disconnect(); cancelAnimationFrame(frame);
    window.removeEventListener('scroll', scheduleUpdate);
    window.removeEventListener('resize', scheduleUpdate);
    document.removeEventListener('pointerdown', onPointerDown);
    navigation.removeEventListener('pointerleave', onPointerLeave);
    navigation.removeEventListener('click', onNavigate); navigation.remove();
  };
}

return { mountProjectNavigation };
},
"shared/gallery.js": function(load) {
const { createLightbox } = load("shared/lightbox.js");
function mountGallery(gallery) {
  const previews = [...gallery.querySelectorAll('[data-src]')];
  const images = previews.map(preview => ({
    src: preview.dataset.src,
    title: preview.dataset.title,
    alt: preview.querySelector('img').alt,
  }));
  const lightbox = createLightbox(images);
  gallery.addEventListener('click', event => {
    const trigger = event.target.closest('[data-gallery-open]');
    if (trigger) lightbox.open(Number(trigger.dataset.galleryOpen), trigger);
  });
}

return { mountGallery };
},
"shared/lightbox.js": function(load) {
const { elementFromHTML, nonBreakingText } = load("shared/dom.js");
function createLightbox(images) {
  const dialog = elementFromHTML(`
    <dialog class="lightbox" aria-label="Просмотр скриншотов">
      <div class="lightbox__toolbar">
        <p class="lightbox__title" aria-live="polite"></p>
        <div class="lightbox__tools">
          <button type="button" data-action="out" aria-label="Уменьшить изображение">−</button>
          <button type="button" class="lightbox__scale" data-action="reset" aria-label="Сбросить масштаб"></button>
          <button type="button" data-action="in" aria-label="Увеличить изображение">+</button>
          <button type="button" data-action="close" aria-label="Закрыть галерею">×</button>
        </div>
      </div>
      <div class="lightbox__stage"><img class="lightbox__image" draggable="false" alt=""></div>
      <div class="lightbox__footer"><button type="button" data-action="previous" aria-label="Предыдущее изображение">←</button><p>← → листать <span>·</span> + − масштаб <span>·</span> перетащить увеличенное изображение <span>·</span> Esc закрыть</p><button type="button" data-action="next" aria-label="Следующее изображение">→</button></div>
    </dialog>`);
  const stage = dialog.querySelector('.lightbox__stage');
  const image = dialog.querySelector('img');
  let index = 0, scale = 1, x = 0, y = 0, drag = null, returnFocus = null;
  let previousOverflow = '';
  let baseWidth = 0, baseHeight = 0;

  function measure() {
    if (!image.naturalWidth || !dialog.open) return;
    const fit = Math.min((stage.clientWidth - 48) / image.naturalWidth, (stage.clientHeight - 32) / image.naturalHeight, 1);
    baseWidth = image.naturalWidth * fit;
    baseHeight = image.naturalHeight * fit;
    image.style.width = `${baseWidth}px`;
    image.style.height = `${baseHeight}px`;
    update();
  }

  function update() {
    const limitX = Math.max(0, (baseWidth * scale - stage.clientWidth) / 2 + 24);
    const limitY = Math.max(0, (baseHeight * scale - stage.clientHeight) / 2 + 16);
    x = Math.max(-limitX, Math.min(limitX, x));
    y = Math.max(-limitY, Math.min(limitY, y));
    image.style.transform = `translate(${x}px, ${y}px) scale(${scale})`;
    stage.classList.toggle('is-zoomed', scale > 1);
    dialog.querySelector('.lightbox__scale').textContent = `${Math.round(scale * 100)}%`;
    dialog.querySelector('[data-action="out"]').disabled = scale <= 1;
    dialog.querySelector('[data-action="in"]').disabled = scale >= 12;
  }

  function zoom(value) { scale = Math.max(1, Math.min(12, value)); update(); }
  function reset() { scale = 1; x = 0; y = 0; update(); }
  function show(nextIndex) {
    index = (nextIndex + images.length) % images.length;
    reset();
    image.src = images[index].src;
    image.alt = images[index].alt;
    dialog.querySelector('.lightbox__title').textContent = nonBreakingText(images[index].title);
    measure();
  }

  const actions = {
    previous: () => show(index - 1), next: () => show(index + 1),
    in: () => zoom(scale * 1.5), out: () => zoom(scale / 1.5),
    reset, close: () => dialog.close(),
  };
  dialog.addEventListener('click', event => {
    const button = event.target.closest('[data-action]');
    if (button) actions[button.dataset.action]();
  });
  dialog.addEventListener('keydown', event => {
    const keys = { ArrowLeft: 'previous', ArrowRight: 'next', '+': 'in', '=': 'in', '-': 'out', '0': 'reset' };
    if (keys[event.key]) { event.preventDefault(); actions[keys[event.key]](); }
    // Native modal dialog traps focus and handles Escape.
  });
  dialog.addEventListener('close', () => {
    document.body.style.overflow = previousOverflow;
    drag = null;
    returnFocus?.focus({ preventScroll: true });
  });
  image.addEventListener('load', measure);
  stage.addEventListener('wheel', event => {
    event.preventDefault();
    zoom(scale * (event.deltaY < 0 ? 1.15 : 1 / 1.15));
  }, { passive: false });
  stage.addEventListener('dblclick', () => scale > 1 ? reset() : zoom(3));
  stage.addEventListener('pointerdown', event => {
    if (scale <= 1 || event.button !== 0) return;
    drag = { pointer: event.pointerId, startX: event.clientX, startY: event.clientY, x, y };
    stage.setPointerCapture(event.pointerId);
    stage.classList.add('is-dragging');
    event.preventDefault();
  });
  stage.addEventListener('pointermove', event => {
    if (!drag || drag.pointer !== event.pointerId) return;
    x = drag.x + event.clientX - drag.startX;
    y = drag.y + event.clientY - drag.startY;
    update();
  });
  const endDrag = () => { drag = null; stage.classList.remove('is-dragging'); };
  stage.addEventListener('pointerup', endDrag);
  stage.addEventListener('pointercancel', endDrag);
  stage.addEventListener('lostpointercapture', endDrag);
  new ResizeObserver(measure).observe(stage);
  document.body.append(dialog);
  return {
    open(nextIndex, trigger) {
      returnFocus = trigger;
      previousOverflow = document.body.style.overflow;
      document.body.style.overflow = 'hidden';
      dialog.showModal();
      show(nextIndex);
      dialog.querySelector('[data-action="close"]').focus();
    },
  };
}

return { createLightbox };
}
};
const cache = new Map();
function load(id) {
  if (!cache.has(id)) cache.set(id, factories[id](load));
  return cache.get(id);
}
load('main.js');
})();
